### ISSUE TITLE
Integrate Concurrent HCL containers into ChronoLog repo

### ISSUE THREAD

**Issue by ibrodkin** [grc-iit/chronolog#14]
the code for concurrent HCL containers that Aparna implemented live on the feature branch of HCL repository.
We need to bring theim into the ChronoLog repository and incorporate into the build

**Comment by fkengun** [comment]
HCL is also developed in our group by Hari. Currently, HCL is added to a submodule to ChronoLog from a forked repo under scs-lab. We, specifically Jaime and Anthony, have the full control of the forked repo under scs-lab. For better development in the future, we need to release Aparna's changes in the scs-lab/hcl and point the submodule to it.

**Comment by ibrodkin** [comment]
pending hcl team review and approval

**Comment by fkengun** [comment]
this is only for git repo, not any code changes

**Comment by fkengun** [comment]
@ibrodkin @aparnasasidharan2017 I accidentally updated the HCL repo in my current branch for API stuff. Since this is a minor update in the submodule. I put it also in PR#44. Pls take a look.
FYI, the submodule in ChronoLog repo is linked to the dev branch of this HCL repo from scs-lab: https://github.com/scs-lab/hcl. As you can see from its title, it is forked from Hari's private repo at https://github.com/hariharan-devarajan/hcl. Itself is forked from HDF-group's repo, which we do not need to care about.

**Comment by fkengun** [comment]
merged into develop
